routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(); 

Route::get('/', 'HomeController@index')->name('index');
Route::get('/product/{id}', 'HomeController@product')->name('product');
Route::get('/car', 'CarController@index')->name('car.index');
Route::get('/car/add', function() {
    return redirect()->route('index');
});
Route::post('/car/add', 'CarController@add')->name('car.add');
Route::delete('/car/remove', 'CarController@remove')->name('car.remove');
Route::post('/car/conclude', 'CarController@conclude')->name('car.conclude');
Route::get('/car/purshase', 'CarController@purshase')->name('car.purshase');
Route::post('/car/cancel', 'CarController@cancel')->name('car.cancel');

Route::group(['prefix' => 'admin'], function () {
    Route::resource('products', 'Admin\ProductController');
});

resources/views/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Loja virtual - @yield('pagina_titulo')</title>

    <link href="/css/app.css" rel="stylesheet">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" href="{{ route('index') }}">Loja</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <div class="navbar-nav">
                    <a class="nav-item nav-link active" href="{{ route('index') }} ">Home <span class="sr-only">(current)</span></a>
                    <a class="nav-item nav-link" href="{{ route('car.index') }}">Carrinho</a>
                    @if (Auth::guest())
                        <li><a class="nav-item nav-link" href="{{ url('/login') }}">Entrar</a></li>
                        <li><a class="nav-item nav-link" href="{{ url('/register') }}">Cadastre-se</a></li>
                    @else
                        <a class="nav-item nav-link" href="{{ route('products.index') }}">Produtos</a>
                        <li>
                            <a class="nav-item nav-link" href="{{ url('/logout') }}"
                                onclick="event.preventDefault();
                                document.getElementById('logout-form').submit();">
                                Logout
                            </a>
                        </li>
                    @endif
                </div>
            </div>
        </nav>
    </header>
    <main>
        @yield('pagina_conteudo')

        @if(!Auth::guest())
            <form id="logout-form" action="{{ url('/logout') }}" method="POST" class="hide">
                {{ csrf_field() }}
            </form>
        @endif
    </main>
    <footer class="footer bg-primary">
        <div class="mt-3 mb-3">© 2018 Copyright</div>
    </footer>
</body>
</html>