routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(); 

Route::get('/', 'HomeController@index')->name('index');
Route::get('/product/{id}', 'HomeController@product')->name('product');
Route::get('/car', 'CarController@index')->name('car.index');
Route::get('/car/add', function() {
    return redirect()->route('index');
});
Route::post('/car/add', 'CarController@add')->name('car.add');
Route::delete('/car/remove', 'CarController@remove')->name('car.remove');
Route::post('/car/conclude', 'CarController@conclude')->name('car.conclude');
Route::get('/car/purshase', 'CarController@purshase')->name('car.purshase');
Route::post('/car/cancel', 'CarController@cancel')->name('car.cancel');

Route::group(['prefix' => 'admin'], function () {
    Route::resource('products', 'Admin\ProductController');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    protected $fillable = [
        'name',
        'description',
        'image',
        'value',
        'character',
        'active'
    ];

    protected $dates = ['deleted_at'];

    public function category()
    {
        return $this->hasMany('App\CategoryProduct','product_id', 'id');
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Product;
use App\CategoryProduct;
use File;

class ProductController extends Controller
{
    public function index()
    {
        $products = Product::with('category')->get();
        return view('admin.product.index', compact('products'));
    }

    public function create()
    {
        return view('admin.product.add');
    }

    public function store(Request $req)
    {
        $file = $req->file('image');
        $image = time() . $file->getClientOriginalName();
        $file->move('storage', $image);
        $url_image = 'http://'.$_SERVER['HTTP_HOST'] . '/storage/' . $image;
        
        Product::create([
            'image' => $url_image,
            'name' => $req->name,
            'description' => $req->description,
            'value' => $req->value,
            'active' => $req->active
        ]);
        
        return redirect()->route('admin.products');
    }
    
    public function edit($id)
    {
        $product = Product::find($id);
        return view('admin.product.edit', compact('product'));
    }
        
    public function update(Request $req, $id)
    {
        $products = $req->all();

        Produto::find($id)->update($products);

        return redirect()->route('admin.products');
    }

    public function destroy(Product $product)
    {
        $product->delete();
        return redirect()->route('admin.products');
    }
}

resources/views/admin/product/_form.blade.php
<div class="form-group">
	<input type="text" name="name" id="nome" required="true" value="{{ isset($product->name) ? $product->name : null }}">
	<label for="nome">Nome</label>
</div>
<div class="form-group">
	<textarea type="text" name="description" id="descricao" required="true">{{ isset($product->description) ? $product->description : null }}</textarea>
	<label for="descricao">Descrição</label>
</div>
<div class="form-group">
	<input type="file" name="image" id="imagem" required="true" value="{{ isset($product->image) ? $product->image : null }}">
</div>
<div class="form-group">
	<input type="text" name="value" id="valor" required="true" value="{{ isset($product->value) ? $product->value : null }}">
	<label for="valor">Valor</label>
</div>
<div class="form-group">
    <div class="row">
        <label for="ativo">Ativo</label>
    </div>
    <div class="row">
      <input name="active" type="radio" id="ativo-s" value="Y" required="required" {{ isset($product->active) && $product->active == 'Y' ? ' checked="checked"' : null }} />
      <label for="ativo-s">Sim</label>
      <input name="active" type="radio" id="ativo-n" value="N" required="required" {{ isset($product->active) && $product->active == 'N' ? ' checked="checked"' : null }} />
      <label for="ativo-n">Não</label>
    </div>
</div>

resources/views/admin/product/_lib.blade.php
@push('scripts')
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
    <script>tinymce.init({ selector:'textarea' });</script>
@endpush

resources/views/admin/product/add.blade.php
@extends('layout')
@section('pagina_titulo', 'Carrinho de compras - Produtos adicionar')

@section('pagina_conteudo')
	<div class="container">
		<div class="row">
			<h3>Adicionar produto</h3>
			<form method="POST" action="{{ route('admin.products.store') }}" enctype="multipart/form-data">
				{{ csrf_field() }}
				@include('admin.product._form')

				<button type="submit" class="btn blue">Salvar</button>
			</form>
		</div>
	</div>
	@include('admin.product._lib')
@endsection

resources/views/admin/product/edit.blade.php
@extends('layout')
@section('pagina_titulo', 'Carrinho de compras - Produtos editar')

@section('pagina_conteudo')
	<div class="container">
		<div class="row">
			<h3>Editar produto "{{ $product->name }}"</h3>
		</div>
		<div class="row">
			<form method="POST" action="" enctype="multipart/form-data">
				@csrf
				@method('put')

				@include('admin.product._form')

				<button type="submit" class="btn blue">Atualizar</button>
			</form>
		</div>
	</div>
	@include('admin.product._lib')
@endsection

resources/views/admin/product/index.blade.php
@extends('layout')
@section('pagina_titulo', 'Carrinho de compras - Produtos')

@section('pagina_conteudo')
	<div class="container">
		<div class="row mt-4">
			<h3>Lista de produtos</h3>
		</div>
		<div class="row mt-3">
			<div class="card-deck">
				@foreach ($products as $product)
					<div class="card">
						<img class="card-img-top" src="{{ $product->image }}">
						<div class="card-body">
							<h5 class="card-title">{{ $product->id }} - {{ $product->name }}</h5>
							<h6 class="card-subtitle mb-2 text-muted">{{ $product->category }}</h6>
							<p class="card-text">{{ $product->description }}</p>
							<a href="{{ route('products.edit', $product->id) }}" class="btn btn-primary">Editar</a>
							<a href="{{ route('products.destroy', $product->id) }}" class="btn btn-danger">Deletar</a>
						</div>
					</div>
				@endforeach
			</div>
		</div>
		<div class="row">
			<a href="{{ route('products.create') }}" class="btn btn-success mt-4">Novo Produto</a>
		</div>
	</div>

@endsection